# Generated by Django 6.0.5 on 2026-06-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255, verbose_name='역할(Role)')),
                ('data_spec', models.TextField(verbose_name='데이터 스펙(Data Spec)')),
                ('core_layout', models.TextField(verbose_name='핵심 레이아웃(Core Layout)')),
                ('tech_stack', models.CharField(max_length=255, verbose_name='기술 스택(Tech Stack)')),
                ('generated_prompt', models.TextField(verbose_name='생성된 프롬프트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
            ],
            options={
                'verbose_name': '프롬프트 생성 이력',
                'verbose_name_plural': '프롬프트 생성 이력',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Gemini API Key를 입력하세요. (비워두면 Rule-based Fallback 사용)', max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시스템 설정',
                'verbose_name_plural': '시스템 설정',
            },
        ),
    ]
